### ISSUE TITLE
Use u64 instead of usize

### ISSUE THREAD

**Issue by nyurik** [hbertoduarte/hilbert_2d#1]
Is there a reason why the lib uses `usize` instead of a more predictable `u64`?  I am not sure there is an reason for the algorithm to be platform dependent.  Would you be ok to merge a PR that changes it? Thx!

**Comment by hbertoduarte** [comment]
At the time, I think the reasoning was that operations with `u64` values would be slowed down or unsupported in 32 bit machines, but since `usize` values are pointer-sized, they would not have this problem. But, to be honest, I'm not sure how big of an impact that would really have.

If I recall correctly, the code can be implemented using any unsigned integer type, with the only difference being the limit on the highest order for the approximation. I think I can sort out a clever implementation for all unsigned integer types using some macros.

**Comment by nyurik** [comment]
I think by now even most of the mobile devices are 64bit... So maybe for the KISS and YAGNI reasons, we could get rid of u32 support?  Because otherwise we end up with this code that by definition is buggy:

https://github.com/stadiamaps/pmtiles-rs/blob/da0123f677d3fe70a438fe65a287997af0d2b13b/src/tile.rs#L13-L18

**Comment by hbertoduarte** [comment]
I can move the implementation into a macro, and use it to implement the same method for all unsigned integer types, the same way that the standard library does it (see [here](https://doc.rust-lang.org/src/core/num/mod.rs.html#923) and [here](https://doc.rust-lang.org/src/core/num/uint_macros.rs.html)).

That way we can preserve API compatibility between versions and eliminate the necessity for these casts between unsigned types. It would look something like this:
```rust
// for usize
hilbert_2d::xy2h_discrete(2usize, 1usize, 2usize, Variant::Hilbert); // or
hilbert_2d::usize::xy2h_discrete(2usize, 1usize, 2usize, Variant::Hilbert);

// for u64 and others
hilbert_2d::u64::xy2h_discrete(2u64, 1u64, 2u64, Variant::Hilbert);
```

**Comment by nyurik** [comment]
that would be awesome, thanks!  In hindsite, I don't even think it makes any sense to implement u64 - the largest encoding is a 32bit one, isn't it?

**Comment by hbertoduarte** [comment]
Well, the Hilbert curve order used in the encoding can be arbitrarily large, and is only limited by the type used to store the 1D indices.

When using `u8`, for example, the limit is the Hilbert curve of order 4: it will map 256 1D indices into a square of side 16. The same way, using `u32` will get you up to the curve of order 16 (2^32 1D indices into a square of side 65536), with larger types going way beyond that.

Anyways, I've published the new changes, hopefully that will help.

**Comment by nyurik** [comment]
Thanks!!!
